[project]
authors = ["figarofuga <61215157+figarofuga@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
polars = ">=1.9.0,<2"
scikit-learn = ">=1.5.2,<2"
pandas = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
pymc = ">=5.17.0,<6"
arviz = ">=0.20.0,<0.21"
bambi = ">=0.14.0,<0.15"
ipykernel = ">=6.29.5,<7"
ipywidgets = ">=8.1.5,<9"
gspread = ">=5.12.4,<6"

[pypi-dependencies]
ortools = ">=9.11.4210, <10"
