[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pandas = ">=2.2.2,<3"
numpy = ">=2.1.1,<3"
matplotlib = ">=3.9.2,<4"
seaborn = ">=0.13.2,<0.14"
polars = ">=1.7.1,<2"
ipykernel = ">=6.29.5,<7"
jupyter = ">=1.1.1,<2"
