[project]
channels = ["conda-forge", "https://repo.prefix.dev/julia-forge"]
description = "Add a short description here"
name = "pixi-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pandas = ">=2.2.2,<3"
matplotlib = ">=3.9.2,<4"
seaborn = ">=0.13.2,<0.14"
polars = ">=1.7.1,<2"
ipykernel = ">=6.29.5,<7"
jupyter = ">=1.1.1,<2"
pymc = ">=5.16.2,<6"
bambi = ">=0.14.0,<0.15"
arviz = ">=0.19.0,<0.20"
