[project]
authors = ["figarofuga <61215157+figarofuga@users.noreply.github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"
